#!/bin/bash

bison -d Praed_Lex.y --warnings=none
flex -t Praed_Lex.l>Praed_Lex.c
gcc -c -o Praed_Lex.o Praed_Lex.c
gcc -c -o Praed_Lex.tab.o Praed_Lex.tab.c
gcc Praed_Lex.o Praed_Lex.tab.o -o Parser

./Parser ./formeln/f1>./result/f1.out
./Parser ./formeln/f2>./result/f2.out
./Parser ./formeln/f3>./result/f3.out
./Parser ./formeln/nested-eqiv>./result/nested-eqiv.out
./Parser ./formeln/test-doubleneg>./result/test-doubleneg.out
./Parser ./formeln/test-equiv>./result/test-equiv.out
./Parser ./formeln/test-impl>./result/test-impl.out
./Parser ./formeln/test-negall>./result/test-negall.out
./Parser ./formeln/test-negand>./result/test-negand.out
./Parser ./formeln/test-negex>./result/test-negex.out
./Parser ./formeln/test-precedence>./result/test-precedence.out
./Parser ./formeln/transitive>./result/transitive.out


echo all outputs created
